export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL'

export const ACCESS_CART = 'ACCESS_CART'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'

export const HANDLE_QUANTITY_REQUEST = 'HANDLE_QUANTITY_REQUEST'
export const HANDLE_QUANTITY_SUCCESS = 'HANDLE_QUANTITY_SUCCESS'
export const HANDLE_QUANTITY_FAIL = 'HANDLE_QUANTITY_FAIL'

export const HANDLE_REMOVE_REQUEST = 'HANDLE_REMOVE_REQUEST'
export const HANDLE_REMOVE_SUCCESS = 'HANDLE_REMOVE_SUCCESS'
export const HANDLE_REMOVE_FAIL = 'HANDLE_REMOVE_FAIL'

export const EMPTY_CART_REQUEST = 'EMPTY_CART_REQUEST'
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS'
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL'


export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST'
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS'
export const FETCH_TOKEN_FAIL = 'FETCH_TOKEN_FAIL'

export const SHIPPING_COUNTRY_REQUEST = 'SHIPPING_COUNTRY_REQUEST'
export const SHIPPING_COUNTRY_SUCCESS = 'SHIPPING_COUNTRY_SUCCESS'
export const SHIPPING_COUNTRY_FAIL = 'SHIPPING_COUNTRY_FAIL'

export const SUBDIVISION_REQUEST = 'SUBDIVISION_REQUEST'
export const SUBDIVISION_SUCCESS = 'SUBDIVISION_SUCCESS'
export const SUBDIVISION_FAIL = 'SUBDIVISION_FAIL'

export const OPTIONS_REQUEST = 'OPTIONS_REQUEST'
export const OPTIONS_SUCCESS = 'OPTIONS_SUCCESS'
export const OPTIONS_FAIL = 'OPTIONS_FAIL'

export const SET_FORM_DATA = 'SET_FORM_DATA'

export const FULFIL_ORDER_REQUEST = 'FULFIL_ORDER_REQUEST'
export const FULFIL_ORDER_SUCCESS = 'FULFIL_ORDER_SUCCESS'
export const FULFIL_ORDER_FAIL = 'FULFIL_ORDER_FAIL'

export const REFRESH_CART = 'REFRESH_CART'



